import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "../styles/globals.css";
import "../styles/normalize.css";
import Navbar from "@/modules/navbar";
import Footer from "@/modules/footer";
import { flattenAttributes } from "@/utils/utils";

const inter = Ubuntu({
  subsets: ["cyrillic"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getNavData(path: string) {
  const baseUrl = `http://192.168.1.6:1337`;
  try {
    const response = await fetch(baseUrl + path, { cache: "no-store" });
    const data = await response.json();
    const flattenedData = flattenAttributes(data);
    return flattenedData;
  } catch (error) {
    console.error(error);
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navData = await getNavData(
    "/api/global?populate[navigation][populate][links]=*&[populate][dropdown][populate][subMenuLinks]=*"
  );

  return (
    <html lang="en">
      <body className={`bg-light dark:bg-dark ${inter.className}`}>
        <Navbar navigation={navData.navigation} dropdown={navData.dropdown} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
